### ISSUE TITLE
GNOME/Fedora style chrome

### ISSUE THREAD

**Issue by purpleidea** [watzon/goshot#1]
As discussed on reddit: https://pay.reddit.com/r/golang/comments/1gvm4y0/goshot_a_tool_to_create_beautiful_screenshots_of/

Readme says:

> Customizable window chrome (macOS, Windows, Linux styles)

But Linux is not mentioned here:

https://github.com/watzon/goshot/wiki/Library-Usage-Chrome

I would love to use this for modern Fedora looking screenshots. I would use [freeze](https://github.com/charmbracelet/freeze/) but that doesn't support Linux either.

I added this issue to get a notification if you add something like Fedora/GNOME style. Please let me know, I'd love to spice up the docs in https://github.com/purpleidea/mgmt/ but I'm not a mac user.

Cheers!

**Comment by watzon** [comment]
Thanks for putting this here! I was going to ask if you'd make an issue for it so that I can track it. Let me tell you where my head is at right now.

As of right now, window themes are defined programmatically using Go, and while the workflow is simple enough it still requires modifications to the code. What I'm starting work on now is an XML based chrome definition that, if done right, should allow the creation of anything from a generic OS window (Windows, macOS, GNOME, etc) to something much more specific like VS Code or Firefox.

We'll see if I can make it happen. If not I'll just fall back to the current way of doing things and add a GNOME variant.

**Comment by watzon** [comment]
Good news! https://github.com/watzon/goshot/releases/tag/v0.3.0
